[build]
    publish = "public"
    functions = "functions"
    command = "npm run build"

[[headers]]
    for = "/*"
    [headers.values]
        Expect-CT = "max-age=0, report-uri='https://panda.report-uri.com/r/d/ct/reportOnly'"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"

# ------------------------------------------------------------------------------
# Redirects
# ------------------------------------------------------------------------------

[[redirects]]
    from = "/1.0.0/*"
    to = "/:splat"
    status = 200
    force = false

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api"
    status = 200
    force = false

[[redirects]]
    from = "/mix/*"
    to = "/.netlify/functions/mix"
    status = 200
    force = false